<a href="https://colab.research.google.com/github/eunzzae/KaggleStudy_MustHave/blob/main/Chap05_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%A3%BC%EC%9A%94_%EA%B0%9C%EB%85%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5-1) 분류와 회귀
## ✅ 분류
* 주어진 피처에 따라 어떤 대상을 정해진(유한한) 범주(타깃값)에 구분해 넣는 작업
(ex. 개와 고양이 구분, 스팸메일과 일반 메일 구분, 질병 검사 결과가 양성인지 음성인지 등)   
→ 타깃값이 두 개 분류는 `이진분류`, 세 개 이상 분류는 `다중분류`

## ✅ 회귀
* 자연현상이나 사회 현상에서 변수 사이 관계
(ex. 학습 시간이 시험 성적에 미치는 영향, 수면의 질이 건강에 미치는 영향, 공장의 재고 수준이 회사 이익에 미치는 영향 등)  
→ 영향을 미치는 변수를 `독립변수`, 영향을 받는 변수를 `종속변수`

* 회귀 : 독립변수와 종속변수 간 관계를 모델링 하는 방법
→ 독립변수 X, 종속변수 Y(단순 선형 회귀)

>* 독립변수(피처)와 종속변수(타깃값) 사이 관계를 기반으로 회귀 모델을 훈련해 **`최적의 회귀계수`**를 찾아야 함

### ✏️ 회귀 평가지표
* 최적의 회귀계수를 구하려면, 예측값과 실젯값의 차이(오차)를 최소화해야 함 ⇒ '데이터에 회귀 모델이 잘 들어맞는다.' 라는 뜻
* 오차가 0이면 회귀 모델이 정확히 일치하지만, 과대적합된 결과임을 의심해봐야 함

>* 회귀 평가지표 값은 작을수록 모델 성능이 좋음

In [ ]:
, mean_tweedie_deviance
import numpy as np

# MAE, MSE, MSLE, R2 임포트

from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error, r2_score

true = np.array([1, 2, 3, 2, 3, 5, 4, 6, 5, 6, 7, 8, 8])
preds = np.array([1, 1, 2, 2, 3, 4, 4, 5, 5, 7, 7, 6, 8])

MAE = mean_absolute_error(true, preds)
MSE = mean_squared_error(true, preds)
RMSE = np.sqrt(MSE)
MSLE = mean_squared_log_error(true, preds)
RMSLE = np.sqrt(mean_squared_log_error(true, preds))
R2 = r2_score(true, preds)

print(f'MAE:\t {MAE:.4f}')
print(f'MSE:\t {MSE:.4f}')
print(f'RMSE:\t {RMSE:.4f}')
print(f'MSLE:\t {MSLE:.4f}')
print(f'RMSLE:\t {RMSLE:.4f}')
print(f'R2:\t {R2:.4f}')

MAE:	 0.5385
MSE:	 0.6923
RMSE:	 0.8321
MSLE:	 0.0296
RMSLE:	 0.1721
R2:	 0.8617


# 5-2) 분류 평가지표
## ✅ 오차행렬
* 실제 타깃값과 예측 타깃값이 어떻게 매칭되는지 보여줌
Tip) '참(T)'오로 시작하면 올바로 예측한 것, '거짓(F)'으로 시작하면 틀린 것  
>*  오차행렬을 활용한 주요 평가지표는 정확도, 정밀도, 재현율, F1 점수가 있으며 **`모두 값이 클수록`** 좋은 지표

### ✏️ 정확도
* 정확도(Accuracy) =  (TN + TP) / (TN + FP + FN + TP)
: 불균형한 데이터를 다룰 때 모델의 신뢰도를 떨어뜨릴 수 있음   
→ 평가지표로 잘 쓰이지 않음

### ✏️ 정밀도
* 정밀도(Precision) = TP / (TP + FP)
: 양성 예측의 정확도, 양성이라고 예측한 값(TP + FP) 중 실제 양성인 값(TP)의 비율  
ex)  실제 스팸 메일(양성)을 일반 메일(음성)로 분류하게 되면 사용자가 불편함을 느끼겠지만 일반 메일을 스팸 메일로 분류할 경우 필요한 메일을 받지 못하는 업무상 차질이 생길 수 있음

### ✏️ 재현율
* 재현율(Recall) =  TP / (TP + FN)
: 민감도 또는 참 양성 비율(TPR), 실제 양성 값(TP + FN) 중 양성으로 잘 예측한 값(TP)의 비율  
ex) 암환자를 음성이 아닌 양성으로 잘못 판단했을 경우 오류의 대가는 재검사를 하는 수준의 비용이지만 양성인 환자를 음성으로 잘못 판단했을 경우 오류의 대가는 생명임

### ✏️ F1 점수
*  F1 점수
: 정밀도와 재현율을 조합한 평가지표

## ✅ 로그손실
* 분류 문제에 타깃값을 확률로 예측할 때 사용하는 평가지표 → 값이 작을수록 좋은 지표

## ✅ ROC 곡선과 AUC
* ROC(Receiver Operating Characteristic)
: 참 양성비율(TPR)에 대한 거짓 양성비율(FPR) 곡선
 >* TPR = TP / (TP + FN) : 실제 Positive 중에 모델이 Positive로 잘 예측한 비율
 >* FPR =  FP / (TN + FP) =  1 - (TN / (TN + FP))

 * AUC(Area Under Curve)
: ROC곡선 아래 면적
Tip) 타깃값(이산값)으로 예측 시 분류 평가지표   
→ 정확도, 정밀도, 재현율, F1 점수
타깃 확률로 예측 시 분류 평가지표   
→ 로그 손실, AUC

# 5-3) 데이터 인코딩
## ✅ 레이블 인코딩
>* 범주형 데이터를 숫자로 일대일 매핑해주는 인코딩 방식



In [ ]:
from sklearn.preprocessing import LabelEncoder # 레이블 인코더

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

# 레이블 인코더 생성
label_encoder = LabelEncoder()
# 레이블 인코딩 적용
fruits_label_encoded = label_encoder.fit_transform(fruits)

print('레이블 인코딩 적용 후 데이터:', fruits_label_encoded)

레이블 인코딩 적용 후 데이터: [3 2 1 0 2 1 1 3]


## ✅ 원-핫 인코딩
>* 여러 값 중 하나만 활성화하는 인코딩 방식
1) 인코딩하려는 피처의 고윳값 개수를 구함
2) 피처의 고윳값 개수만큼 열을 추가
3) 각 고윳값에 해당하는 열에 1을 표시하고 나머지 열에는 0을 표시
단점: 열 개수가 많아져서 메모리 사용량 늘어나므로 모델 훈련속도 저하

>* 명목형 피처 고윳값이 **많을 때**
1) 비슷한 고윳값끼리 그룹화
2) 빈도가 낮은 고윳값을 '기타(etc)'로 처리
3) 다른 인코딩 적용 : 타깃 인코딩, 프리퀀시 인코딩 등 그 외 기법 사용




In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

# 레이블 인코더, 원-핫 인코더 생성
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

# 레이블 인코딩 적용(문자 데이터 -> 숫자 데이터)
fruits_label_encoded = label_encoder.fit_transform(fruits)
# 원-핫 인코딩 적용
fruits_onehot_encoded = onehot_encoder.fit_transform(fruits_label_encoded.reshape(-1, 1))

print('원-핫 인코딩 적용 후 데이터:\n', fruits_onehot_encoded.toarray())

원-핫 인코딩 적용 후 데이터:
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


* 원-핫 인코딩은 대부분 값이 0인 희소행렬을 만듦
* 희소행렬은 메모리 낭비가 심해서 변환 결과를 압축된 형태인 CSR형태로 돌려줌
  - .toarray()는 CSR 형태의 행렬을 일반 배열로 바꿔주는 역할
  - get_dummies()함수를 사용하면 간단하게 구현 가능

In [ ]:
import pandas as pd

pd.get_dummies(fruits)

귤  바나나  블루베리  사과
0  0    0     0   1
1  0    0     1   0
2  0    1     0   0
3  1    0     0   0
4  0    0     1   0
5  0    1     0   0
6  0    1     0   0
7  0    0     0   1

# 5-4) 피처 스케일링
>* 서로 다른 피처 값의 범위(최댓값-최솟값)가 일치하도록 조정
⇒ 데이터마다 값의 범위가 다르면 모델 훈련 X

## ✅ min-max 정규화
>* 피처 값의 범위를 0~1로 조정하는 기법
⇒ 모든 값의 범위를 0-1 사이로 맞출 때 주로 사용

※ 이상치가 너무 크거나 작을 때 결과값은 적절하지 않음

In [ ]:
import pandas as pd

height_weight_dict = {'키' : [1.7, 1.5, 1.8], '몸무게':[75, 55, 60]}
df = pd.DataFrame(height_weight_dict, index=['광일', '혜성', '덕수'])

print(df)

      키  몸무게
광일  1.7   75
혜성  1.5   55
덕수  1.8   60


In [ ]:
from sklearn.preprocessing import MinMaxScaler

# min-max 정규화 객체 생성
scaler = MinMaxScaler()

# min-max 정규화 적용
scaler.fit(df)
df_scaled = scaler.transform(df)

print(df_scaled)

[[0.66666667 1.        ]
 [0.         0.        ]
 [1.         0.25      ]]


## ✅ 표준화
* 평균이 0, 분산이 1이 되도록 피처 값 조정  
⇒ 상한과 하한 값이 없음

In [ ]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# 표준화 적용
df_scaled = scaler.fit_transform(df)

print(df_scaled)

[[ 0.26726124  1.37281295]
 [-1.33630621 -0.98058068]
 [ 1.06904497 -0.39223227]]


# 5-5) 교차 검증
>* 훈련 데이터로 모델 훈련하고, 테스트 데이터로 예측해 모델 성능 측정  

<성능을 검증하지 않으면 문제 발생>  
1) 모델 과대적합될 가능성 존재  
2) 모델 성능 확인 어려움

## ✅ K 폴드 교차 검증
* 절차   
1) 전체 훈련 데이터를 K개 그룹으로 나눔  
2) 그룹 하나는 검증데이터, 나머지 K-1개는 훈련 데이터로 지정  
3) 훈련 데이터로 모델을 훈련하고, 검증데이터로 평가  
4) 평가점수 기록  
5) 검증 데이터를 다른 그룹으로 바꿔가며 2~4절차 K번 반복  
6) K개 검증 평가 점수 평균 구함  

In [ ]:
import numpy as np
from sklearn.model_selection import KFold

data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

folds = KFold(n_splits=5, shuffle=False)

for train_idx, valid_idx in folds.split(data):
  print(f'훈련 데이터: {data[train_idx]}, 검증 데이터: {data[valid_idx]}')

훈련 데이터: [2 3 4 5 6 7 8 9], 검증 데이터: [0 1]
훈련 데이터: [0 1 4 5 6 7 8 9], 검증 데이터: [2 3]
훈련 데이터: [0 1 2 3 6 7 8 9], 검증 데이터: [4 5]
훈련 데이터: [0 1 2 3 4 5 8 9], 검증 데이터: [6 7]
훈련 데이터: [0 1 2 3 4 5 6 7], 검증 데이터: [8 9]


## ✅ 층화 K 폴드 교차 검증
* 타깃값이 `불균등`하게 분포되어 있는 경우 사용   
⇒ 타깃값을 골고루 분포되게 폴드를 나눔
(분류문제에만 사용됨)

*  Fold 5에는 스팸이라는 타깃값이 존재하지 않음 -> 층화 K 폴드 사용

In [ ]:
y = np.array(['스팸']*5 + ['일반']*45)

folds = KFold(n_splits=5, shuffle=True) # K 폴드 교차 검증

for idx, (train_idx, valid_idx) in enumerate(folds.split(y)):
  print(f'Fold {idx+1} 검증 데이터 타깃값:')
  print(y[valid_idx], '\n')

Fold 1 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 2 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 3 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 4 검증 데이터 타깃값:
['스팸' '스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 5 검증 데이터 타깃값:
['일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 



In [ ]:
from sklearn.model_selection import StratifiedKFold

X = np.array(range(50))
Y = np.array(['스팸']*5 + ['일반']*45)

folds = StratifiedKFold(n_splits=5) # 층화 K 폴드 교차 검증

for idx, (train_idx, valid_idx) in enumerate(folds.split(X, Y)):
  print(f'Fold {idx+1} 검증 데이터 타깃값:')
  print(Y[valid_idx], '\n')


Fold 1 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 2 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 3 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 4 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

Fold 5 검증 데이터 타깃값:
['스팸' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반' '일반'] 

